// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGvy0YOS3WbIOEaf5ORPpSOjrXsFVd3WM',
    appId: '1:41820155048:web:6e411940c4a3cd0e21e69d',
    messagingSenderId: '41820155048',
    projectId: 'cred-app-aa333',
    authDomain: 'cred-app-aa333.firebaseapp.com',
    storageBucket: 'cred-app-aa333.firebasestorage.app',
    measurementId: 'G-2KCZ7GR031',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9E7ZiUKV0z0SnuiH_IiWlb94jHfn5Row',
    appId: '1:41820155048:android:db04e4063ce303de21e69d',
    messagingSenderId: '41820155048',
    projectId: 'cred-app-aa333',
    storageBucket: 'cred-app-aa333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl1T1k_nEjLG0evmY0lMtrDFPhDpUh3Io',
    appId: '1:41820155048:ios:0bf181c5b2fa9f0d21e69d',
    messagingSenderId: '41820155048',
    projectId: 'cred-app-aa333',
    storageBucket: 'cred-app-aa333.firebasestorage.app',
    iosBundleId: 'com.example.creditCardTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl1T1k_nEjLG0evmY0lMtrDFPhDpUh3Io',
    appId: '1:41820155048:ios:0bf181c5b2fa9f0d21e69d',
    messagingSenderId: '41820155048',
    projectId: 'cred-app-aa333',
    storageBucket: 'cred-app-aa333.firebasestorage.app',
    iosBundleId: 'com.example.creditCardTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGvy0YOS3WbIOEaf5ORPpSOjrXsFVd3WM',
    appId: '1:41820155048:web:169e36c6490f434f21e69d',
    messagingSenderId: '41820155048',
    projectId: 'cred-app-aa333',
    authDomain: 'cred-app-aa333.firebaseapp.com',
    storageBucket: 'cred-app-aa333.firebasestorage.app',
    measurementId: 'G-FEQXDWZP7G',
  );
}
